POST http://kitaika39.ru:8000/api/addtocart
Content-Type: application/json

{
  "order_id": 1,
  "product_id": 1,
  "count": 1
}

###
PUT http://kitaika39.ru:8000/api/updateorder/1
Content-Type: application/json

{
  "last_time": "10000",
  "phone_number": "+7800553535",
  "name": "Илья Обухов",
  "info": "налейте мне соуса побольше пжл",
  "address": "Державина 100",
  "take_type": "pickup",
  "payment_type": "card"
}


###
POST http://localhost:8000/api/createproduct
Content-Type: application/json

{
  "label": "Тестовый продукт",
  "price": 800,
  "category_id": 2,
  "about": "тестетстс",
  "image_path": "path1231230",
  "calories": 300
}

###
POST http://localhost:8000/api/addtocart/
Content-Type: application/json

{
  "order_id": "1",
  "product_id": "2",
  "count": "1"
}

###
POST http://localhost:8000/api/addtocart/
Accept: application/json

{
"order_id": 2
}
